"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto"),WebSocket=require("ws");
const PORT=process.env.PORT||3000,HOST="0.0.0.0",MAX=20,TICK=50,DURATION=180000;
const rooms=new Map(),files={"/":"index.html","/index.html":"index.html","/game.js":"game.js","/style.css":"style.css"};
const maps={cyber:"Cyber City",factory:"Factory",jungle:"Jungle Ruins"};
const weapons={pulse:{damage:20,speed:24,cool:650},plasma:{damage:32,speed:18,cool:1000}};
function send(w,o){if(w&&w.readyState===WebSocket.OPEN)try{w.send(JSON.stringify(o))}catch(_){} }function broadcast(r,o){send(r.host,o);r.players.forEach(p=>send(p.ws,o))}
function name(v){return typeof v==="string"?v.replace(/[\u0000-\u001F\u007F]/g," ").replace(/\s+/g," ").trim().slice(0,20):""}
function code(){let c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";for(let n=0;n<500;n++){let x="";for(let i=0;i<4;i++)x+=c[crypto.randomInt(c.length)];if(!rooms.has(x))return x}return null}
function spawn(i){return{x:-60+(i%5)*30,z:-36+Math.floor(i/5)*24}}
function state(r){return{type:"state",phase:r.phase,map:r.map,mapName:maps[r.map],remaining:r.phase==="playing"?Math.max(0,Math.ceil((r.end-Date.now())/1000)):0,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,x:p.x,z:p.z,yaw:p.yaw,hp:p.hp,kills:p.kills,alive:p.alive,weapon:p.weapon})),projectiles:r.bullets.map(b=>({id:b.id,x:b.x,y:2,z:b.z}))}}
function board(r){return[...r.players.values()].map(p=>({name:p.name,kills:p.kills,hp:p.hp,alive:p.alive})).sort((a,b)=>b.kills-a.kills||b.hp-a.hp)}
function sync(r){broadcast(r,state(r));send(r.host,{type:"hostBoard",players:board(r)})}
function reset(p,i){let s=spawn(i);Object.assign(p,{x:s.x,z:s.z,hp:100,kills:0,alive:true,weapon:"pulse",lastShot:0,lastMelee:0,lastDash:0,input:{f:0,b:0,l:0,r:0}})}
function start(r){if(r.phase!=="lobby")return;r.phase="playing";r.end=Date.now()+DURATION;r.bullets=[];let i=0;r.players.forEach(p=>reset(p,i++));broadcast(r,{type:"matchStart",map:r.map,mapName:maps[r.map],duration:DURATION/1000});sync(r);r.timer=setInterval(()=>tick(r),TICK)}
function finish(r,reason){if(r.phase==="ended")return;r.phase="ended";clearInterval(r.timer);r.timer=null;broadcast(r,{type:"matchEnd",reason,ranking:board(r).map((p,i)=>({rank:i+1,...p}))});sync(r)}
function hit(r,a,t,d){if(!t.alive)return;t.hp-=d;if(t.hp<=0){t.hp=0;t.alive=false;if(a&&a.id!==t.id)a.kills++;send(t.ws,{type:"eliminated",respawnIn:2000});setTimeout(()=>{if(r.phase==="playing"&&r.players.has(t.id)){let s=spawn(Math.floor(Math.random()*20));t.x=s.x;t.z=s.z;t.hp=100;t.alive=true}},2000)}}
function tick(r){if(r.phase!=="playing")return;let now=Date.now();r.players.forEach(p=>{if(!p.alive)return;let dx=(p.input.r?1:0)-(p.input.l?1:0),dz=(p.input.b?1:0)-(p.input.f?1:0);if(dx||dz){let l=Math.hypot(dx,dz);dx/=l;dz/=l;let c=Math.cos(p.yaw),s=Math.sin(p.yaw);p.x+=(dx*c-dz*s)*7*TICK/1000;p.z+=(dx*s+dz*c)*7*TICK/1000}p.x=Math.max(-88,Math.min(88,p.x));p.z=Math.max(-58,Math.min(58,p.z))});let nb=[];for(let b of r.bullets){b.x+=Math.cos(b.a)*b.sp*TICK/1000;b.z+=Math.sin(b.a)*b.sp*TICK/1000;if(Math.abs(b.x)>90||Math.abs(b.z)>60)continue;let hitit=false;for(let t of r.players.values())if(t.alive&&t.id!==b.owner&&Math.hypot(b.x-t.x,b.z-t.z)<2.2){hit(r,r.players.get(b.owner),t,b.d);hitit=true;break}if(!hitit)nb.push(b)}r.bullets=nb;if(now>=r.end){finish(r,"TIME UP");return}if(now-r.last>80){r.last=now;sync(r)}}
function create(ws,m){let n=name(m.name);if(!n)return send(ws,{type:"error",message:"Enter your name."});let c=code();if(!c)return;let r={code:c,host:ws,hostName:n,players:new Map,next:1,map:"cyber",phase:"lobby",end:0,bullets:[],timer:null,last:0};rooms.set(c,r);ws.ctx={role:"host",room:r};send(ws,{type:"created",role:"host",code:c,max:MAX,maps})}
function join(ws,m){let c=typeof m.code==="string"?m.code.trim().toUpperCase():"",n=name(m.name),r=rooms.get(c);if(!/^[A-Z0-9]{4}$/.test(c)||!n)return send(ws,{type:"error",message:"Enter a valid name and room code."});if(!r)return send(ws,{type:"error",message:"Room not found."});if(r.players.size>=MAX)return send(ws,{type:"error",message:"Room is full."});if(r.phase==="ended")return send(ws,{type:"error",message:"Match has ended."});let id=r.next++,s=spawn(r.players.size),p={id,name:n,ws,x:s.x,z:s.z,yaw:0,hp:100,kills:0,alive:true,weapon:"pulse",lastShot:0,lastMelee:0,lastDash:0,input:{f:0,b:0,l:0,r:0}};r.players.set(id,p);ws.ctx={role:"player",room:r,id};send(ws,{type:"joined",role:"player",code:c,id,name:n,max:MAX});if(r.phase==="playing")send(ws,{type:"lateJoin"});sync(r)}
function msg(ws,m){let c=ws.ctx;if(m.type==="create")return create(ws,m);if(m.type==="join")return join(ws,m);if(!c)return;if(m.type==="map"&&c.role==="host"&&c.room.phase==="lobby"&&maps[m.map]){c.room.map=m.map;return broadcast(c.room,{type:"mapChanged",map:m.map,mapName:maps[m.map]})}let r=c.room,p=r.players.get(c.id);if(m.type==="start"&&c.role==="host")return start(r);if(!p||!p.alive||r.phase!=="playing")return;if(m.type==="input"){p.input={f:!!m.input?.forward,b:!!m.input?.back,l:!!m.input?.left,r:!!m.input?.right};if(Number.isFinite(m.yaw))p.yaw=m.yaw}if(m.type==="weapon"&&weapons[m.weapon])p.weapon=m.weapon;if(m.type==="dash"&&Date.now()-p.lastDash>1000){p.lastDash=Date.now();p.x+=Math.cos(p.yaw)*12;p.z+=Math.sin(p.yaw)*12}if(m.type==="melee"&&Date.now()-p.lastMelee>500){p.lastMelee=Date.now();for(let t of r.players.values())if(t.id!==p.id&&t.alive&&Math.hypot(t.x-p.x,t.z-p.z)<5){let a=Math.atan2(t.z-p.z,t.x-p.x),d=Math.atan2(Math.sin(a-p.yaw),Math.cos(a-p.yaw));if(Math.abs(d)<2)hit(r,p,t,25)}}if(m.type==="shoot"){let w=weapons[p.weapon],now=Date.now();if(now-p.lastShot>=w.cool){p.lastShot=now;r.bullets.push({id:crypto.randomUUID(),owner:p.id,x:p.x,z:p.z,a:p.yaw,sp:w.speed,d:w.damage})}}}
function close(ws){let c=ws.ctx;if(!c)return;ws.ctx=null;let r=c.room;if(c.role==="host"){clearInterval(r.timer);rooms.delete(r.code);r.players.forEach(p=>send(p.ws,{type:"roomClosed",message:"Host left the room."}))}else{r.players.delete(c.id);sync(r)}}
const server=http.createServer((req,res)=>{let u=(req.url||"/").split("?")[0];if(u==="/healthz"){res.writeHead(200);return res.end("ok")}let f=files[u];if(!f){res.writeHead(404);return res.end("Not found")}fs.readFile(path.join(__dirname,"public",f),(e,d)=>{if(e){res.writeHead(500);return res.end("File unavailable")}let ext=path.extname(f),ct=ext===".html"?"text/html":ext===".js"?"text/javascript":"text/css";res.writeHead(200,{"Content-Type":ct+"; charset=utf-8","Cache-Control":"no-cache"});res.end(d)})});
const wss=new WebSocket.Server({server,maxPayload:8192,perMessageDeflate:false});wss.on("connection",ws=>{ws.ctx=null;ws.on("message",d=>{try{let m=JSON.parse(d.toString());if(m&&typeof m.type==="string")msg(ws,m)}catch(e){send(ws,{type:"error",message:"Server error."})}});ws.on("close",()=>close(ws))});server.listen(PORT,HOST,()=>console.log("Battle Arena 3D on "+PORT));
